sudo: false

language:
  - cpp

addons:
  apt:
    packages:
    - libgtest-dev

install:
  - mkdir ~/gtest
  - cp -R /usr/src/gtest/ ~/
  - cd ~/gtest
  - cmake .
  - make
  - cd "${TRAVIS_BUILD_DIR}"

script:
  - export CMAKE_PREFIX_PATH=CMAKE_PREFIX_PATH:/home/travis/gtest
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest -V && ctest