sudo: false

language:
  - cpp

addons:
  apt:
    packages:
    - libgtest-dev

install:
#  - sudo apt-get install libgtest-dev
  - mkdir ~/gtest
  - cp -R /usr/src/gtest ~/gtest/
  - cd ~/gtest
  - cmake .
  - make
  - mv libgtest* /usr/local/lib/
  - cd "${TRAVIS_BUILD_DIR}"

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest -V && ctest