sudo: false

language: cpp
compiler: g++

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libgtest-dev
    - g++-4.8

install:
  # Compiler
  - export CXX="g++-4.8"
  # GTest
  - mkdir ~/gtest
  - cp -R /usr/src/gtest/ ~/
  - cd ~/gtest
  - cmake .
  - make
  - cd "${TRAVIS_BUILD_DIR}"

script:
  - export CMAKE_PREFIX_PATH=CMAKE_PREFIX_PATH:/home/travis/gtest
  - mkdir build
  - cd build
  - gcc --version
  - g++ --version
  - cmake ..
  - make
  - ctest -V && ctest